# _config.yml

title: "National Digital Capacity Library - Sri Lanka"
description: "A comprehensive digital library for Digital Sri Lanka, tailored to diverse user personas."
baseurl: "/capacity-building" # et to repository name; English is at root 
url: "https://ictasl.github.io/capacity-building/" # Base hostname & protocol

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Supported languages
languages:
  - en
  - si
  - ta
